name    'puppet-gitlab_server'
version '0.0.1'
project_page 'https://github.com/openstack-hyper-v/puppet-gitlab_server'
source 'https://github.com/openstack-hyper-v/puppet-gitlab_server'
author 'Peter J. Pouliot'
license 'Apache License, Version 2.0'
summary 'A module for configuring and controlling a GitLab server'
description 'A module for configuring and controlling a GitLab server'

dependency 'openstack-hyper-v/puppet-gitlab', '>=0.0.8'
dependency 'puppetlabs/vcsrepo'
